### ISSUE TITLE
Having a core module containing shared items

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/dev#5]
Actually we have a dependency to the "dev" module to re-use some items. 
It is preferable to have a common shared module (called "core" for instance) that will contain a basic/generic Items not included on the kernel, but could be reused by several other projects.

The actual "dev" module has a dependency to other modules which we do not need them (CristalXMLDB and CristalLDAP). 

If we will have a "core" (CristalCore) module, you can change the "dev" module to have a dependency to this "core" module, alongside with the other actual modules. In our side, we will have just a dependency to the "core" module, not the "dev" one.

"dev" module could have another name, like "demo" module.

**Comment by abranson** [comment]
This is fine, but the reason these items are in a separate module and not included in the kernel (as they previously were) is because although they are basic implementations of resource factories, they are not intended to be, and I don't think they could ever be, generic. They are examples, and sticking to them will limit how you can extend resource Items. They are recommended for use as a tutorial on how Item designers can be implemented.
Along with the dependencies on the XMLDB and LDAP modules, I think the example 'dev' agent should also be moved to the new demo module.

**Comment by kovax** [comment]
I can understand both points. Managing the lifecycle of definitions is
fundamental activity required to have working system, therefore it is
natural for an user of the kernel to expect to have some firm support for
them. On the other hand, the Lifecycle of a definition could be very domain
specific.

The best analogy are the CRUD operations of database objects. The framework
provides them, and the user can override and add new ones.

So I guess the best approach is to consider 'dev module' as the CRUD
implementation, and such implementation I believe it is generic.
